export const data = [   {id:1,eng:'implement',rus:'реализовывать'}, 
    {id:2,eng:'select',rus:'выбирать'},
    {id:3,eng:'advance',rus:'продвигать'},
    {id:4,eng:'certain',rus:'определенный'},
    {id:5,eng:'necessary',rus:'необходимый'},
    {id:6,eng:'flow',rus:'поток'},
    {id:7,eng:'opacity',rus:'непрозрачность'},
    {id:8,eng:'template',rus:'шаблон'},
    {id:9,eng:'override',rus:'обойти сист. без.'},
    {id:10,eng:'preserve',rus:'защищать'},
    {id:11,eng:'drop',rus:'уронить'},
    {id:12,eng:'usage',rus:'использование'},
    {id:13,eng:'nut',rus:'гайка'},
    {id:14,eng:'scope',rus:'масштаб охвата'},
    {id:15,eng:'bolt',rus:'болт'},
    {id:16,eng:'edit',rus:'редактировать'},
    {id:17,eng:'during',rus:'в течение'},
    {id:18,eng:'snap',rus:'клик'},
    {id:19,eng:'thread',rus:'резьба'},
    {id:20,eng:'network',rus:'сеть'},
    {id:21,eng:'plug',rus:'затыкать'},
    {id:22,eng:'latest',rus:'последний'},
    {id:23,eng:'able',rus:'способный'},
    {id:24,eng:'trip',rus:'путешествие'},
    {id:25,eng:'deal',rus:'иметь дело'},
    {id:26,eng:'tradeoff',rus:'компромисc'},
    {id:27,eng:'indirect',rus:'косвенный'},
    {id:28,eng:'short term',rus:'краткосрочный'},
    {id:29,eng:'might',rus:'мочь, мощь'},
    {id:30,eng:'decide',rus:'решать'},
    {id:31,eng:'sure',rus:'уверенн, конечно'},
    {id:32,eng:'choice',rus:'выбор'},
    {id:33,eng:'intent',rus:'цель'},
    {id:34,eng:'buy',rus:'купить'},
    {id:35,eng:'margin',rus:'поле (отступ внешний)'},
    {id:36,eng:'flex',rus:'сгибаться'},
    {id:37,eng:'grass',rus:'трава'},
    {id:38,eng:'where',rus:'куда, где'},
    {id:39,eng:'summary',rus:'резюме, заключение'},
    {id:40,eng:'to',rus:'к'},
    {id:41,eng:'enough',rus:'достаточно'},
    {id:42,eng:'generally',rus:'в главном'},
    {id:43,eng:'brief retelling',rus:'краткий пересказ'},
    {id:44,eng:'independence',rus:'независимость'},
    {id:45,eng:'response ',rus:'отклик'},
    {id:46,eng:'hid',rus:'спрятать'},
    {id:47,eng:'seize',rus:'захватывать'},
    {id:48,eng:'snippets',rus:'фрагменты'},
    {id:49,eng:'middle',rus:'середина'},
    {id:50,eng:'switch',rus:'выключатель'},
    {id:51,eng:'several',rus:'несколько'},
    {id:52,eng:'wheel',rus:'рулевое колесо'},
    {id:53,eng:'sources',rus:'источники'},
    {id:54,eng:'viewport',rus:'окно простмотра'},
    {id:55,eng:'adjacent',rus:'сосед '},
    {id:56,eng:'application',rus:'приложение'},
    {id:57,eng:'lighthouse',rus:'маяк'},
    {id:58,eng:'recorder',rus:'регистратор, магнитофон'},
    {id:59,eng:'align',rus:'выровнять (текст)'},
    {id:60,eng:'overview',rus:'обзор'},
    {id:61,eng:'drag',rus:'тащить'},
    {id:62,eng:'performance',rus:'производительность'},
    {id:63,eng:'since',rus:'с'},
    {id:64,eng:'host',rus:'хозяин'},
    {id:65,eng:'anyone',rus:'кто угодно'},
    {id:66,eng:'heap',rus:'куча'},
    {id:67,eng:'few',rus:'несколько'},
    {id:68,eng:'redirect',rus:'перенаправить'},
    {id:69,eng:'through',rus:'через, поперек'},
    {id:70,eng:'background ',rus:'фон'},
    {id:71,eng:'still ',rus:'всё ещё'},
    {id:72,eng:'pretty small',rus:'довольно маленький'},
    {id:73,eng:'task',rus:'задача, задание'},
    {id:74,eng:'provide',rus:'предоставлять'},
    {id:75,eng:'lot',rus:'много'},
    {id:76,eng:'plugin',rus:'вставной'},
    {id:77,eng:'request',rus:'запрос'},
    {id:78,eng:'strange',rus:'странный'},
    {id:79,eng:'enqueue',rus:'поставить в очередь'},
    {id:80,eng:'share',rus:'поделиться доступом'},
    {id:81,eng:'verbose',rus:'многословный'},
    {id:82,eng:'hold',rus:'держать'},
    {id:83,eng:'overflow',rus:'переполнение'},
    {id:84,eng:'display',rus:'экран'},
    {id:85,eng:'sign',rus:'знак'},
    {id:86,eng:'via',rus:'с помощью'},
    {id:87,eng:'apply',rus:'применять'},
    {id:88,eng:'ink',rus:'чернила'},
    {id:89,eng:'signature',rus:'подпись'},
    {id:90,eng:'there',rus:'там'},
    {id:91,eng:'disable',rus:'отключить'},
    {id:92,eng:'shape',rus:'форма, формировать'},
    {id:93,eng:'in recent years',rus:'в недавние годы'},
    {id:94,eng:'background',rus:'происхождение, история'},
    {id:95,eng:'vitals',rus:'жизнено важные органы'},
    {id:96,eng:'pan',rus:'лоток, кастрюля, протвень,'},
    {id:97,eng:'snapshot',rus:'снимок'},
    {id:98,eng:'among',rus:'среди'},
    {id:99,eng:'rest',rus:'остаток, отдых'},
    {id:100,eng:'select',rus:'выбирать'},
    {id:101,eng:'strengyhen',rus:'укреплять, усиливать'},
    {id:102,eng:'relate',rus:'относится, связывать'},
    {id:103,eng:'highlight',rus:'важный момент (выделенный)'},
    {id:104,eng:'early days',rus:'в первые дни, изначально'},
    {id:105,eng:'attach',rus:'прикладывать, прикреплять'},
    {id:106,eng:'was to do',rus:'были сделаны'},
    {id:107,eng:'complete',rus:'полностью законченный'},
    {id:108,eng:'issues',rus:'спорный вопрос'},
    {id:109,eng:'increase',rus:'увеличение'},
    {id:110,eng:'display',rus:'отображать'},
    {id:111,eng:'popup',rus:'всплывающий, выскакивающий'},
    {id:112,eng:'momentum',rus:'момент'},
    {id:113,eng:'pricing',rus:'ценообразование'},
    {id:114,eng:'capitalize',rus:'извлекать выгоду'},
    {id:115,eng:'strong',rus:'крепкий'},
    {id:116,eng:'resolve a dispute',rus:'разрешить спор (разобрать)'},
    {id:117,eng:'along',rus:'вдоль'},
    {id:118,eng:'which',rus:'который, какой, что'},
    {id:119,eng:'ribbon',rus:'лента'},
    {id:120,eng:'ceiling',rus:'потолок'},
    {id:121,eng:'entire',rus:'весь, полностью'},
    {id:122,eng:'choose',rus:'выбирать'},
    {id:123,eng:'subscriber',rus:'подписчик'},
    {id:124,eng:'remote',rus:'удаленный, дистанционный'},
    {id:125,eng:'believe',rus:'верить'},
    {id:126,eng:'bookmark',rus:'закладка в книге'},
    {id:127,eng:'eraser',rus:'ластик'},
    {id:128,eng:'case',rus:'ситуация, случай'},
    {id:129,eng:'health',rus:'здоровье'},
    {id:130,eng:'chair',rus:'стул'},
    {id:131,eng:'attachment',rus:'вложение, приложение'},
    {id:132,eng:'fork',rus:'вилка'},
    {id:133,eng:'hear',rus:'слышать'},
    {id:134,eng:'xxx',rus:'xxx'},
    {id:135,eng:'leave',rus:'покидать'},
    {id:136,eng:'ask',rus:'спрашивать'},
    {id:137,eng:'turn',rus:'поворачивать'},
    {id:138,eng:'actions',rus:'действия'},
    {id:139,eng:'available',rus:'доступный'},
    {id:140,eng:'late',rus:'поздний'},
    {id:141,eng:'wrong',rus:'неправильный, неверный'},
    {id:142,eng:'rectangle',rus:'прямоугольник'},
    {id:143,eng:'whole',rus:'весь'},
    {id:144,eng:'collaborate',rus:'сотрудничать'},
    {id:145,eng:'sensitive',rus:'чувствительный'},
    {id:146,eng:'poor',rus:'бедняк, бедный'},
    {id:147,eng:'cloud',rus:'облако'},
    {id:148,eng:'vertex',rus:'вершина'},
    {id:149,eng:'tutorial',rus:'руководство'},
    {id:150,eng:'forward',rus:'вперед'},
    {id:151,eng:'measure',rus:'измерять'},
    {id:152,eng:'enterprise',rus:'предприятие'},
    {id:153,eng:'software',rus:'ПО'},
    {id:154,eng:'hidden',rus:'скрытый'},
    {id:155,eng:'view',rus:'вид, смотреть'},
    {id:156,eng:'ship',rus:'судно'},
    {id:157,eng:'education',rus:'образование'},
    {id:158,eng:'include',rus:'включая'},
    {id:159,eng:'detailed',rus:'детализированный, подробный'},
    {id:160,eng:'dispatch',rus:'отправка'},
    {id:161,eng:'handl',rus:'обрабатывать'},
    {id:162,eng:'offere',rus:'предложение'},
    {id:163,eng:'hub',rus:'центр деятельности'},
    {id:164,eng:'feature',rus:'особенность, штуковина'},
    {id:165,eng:'prerequisites',rus:'предпосылки'},
    {id:166,eng:'customize',rus:'настроить'},
    {id:167,eng:'enable',rus:'включить, дать возможность'},
    {id:168,eng:'demand',rus:'требовать'},
    {id:169,eng:'pieces',rus:'части'},
    {id:170,eng:'wonder',rus:'удивление, чудо'},
    {id:171,eng:'essential',rus:'основы'},
    {id:172,eng:'salary',rus:'зарплата'},
    {id:173,eng:'layout',rus:'макет'},
    {id:174,eng:'xxx',rus:'xxx'},
    {id:175,eng:'look like',rus:'быть похожим '},
    {id:176,eng:'should',rus:'должен'},
    {id:177,eng:'own',rus:'свой собственный'},
    {id:178,eng:'feed',rus:'поток скармливаемой информации'},
    {id:179,eng:'split',rus:'расколоть на части'},
    {id:180,eng:'native',rus:'натуральный, естественный'},
    {id:181,eng:'side',rus:'сторона, бок'},
    {id:182,eng:'basic',rus:'базовый'},
    {id:183,eng:'extra',rus:'дополнительный'},
    {id:184,eng:'could',rus:'мог'},
    {id:185,eng:'entrie',rus:'вход'},
    {id:186,eng:'chapter',rus:'глава'},
    {id:187,eng:'improve',rus:'улучшать'},
    {id:188,eng:'concurrency',rus:'параллелизм'},
    {id:189,eng:'instead',rus:'вместо, взамен'},
    {id:190,eng:'let',rus:'позволять, допускать'},
    {id:191,eng:'however',rus:'однако'},
    {id:192,eng:'their',rus:'их'},
    {id:193,eng:'case sensitive',rus:'с учетом регистра'},
    {id:194,eng:'maintain',rus:'поддерживать'},
    {id:195,eng:'xxx',rus:'xxx'},
    {id:196,eng:'government',rus:'правительство'},
    {id:197,eng:'rules',rus:'правила'},
    {id:198,eng:'pane',rus:'панель'},
    {id:199,eng:'bit',rus:'немного'},
    {id:200,eng:'select',rus:'выбирать'},
    {id:201,eng:'link',rus:'связь, связать'},
    {id:202,eng:'as well as',rus:'а также'},
    {id:203,eng:'arrow',rus:'стрелка'},
    {id:204,eng:'fast forward',rus:'промотаем время вперед'},
    {id:205,eng:'so',rus:'таким оброзом'},
    {id:206,eng:'most of the people',rus:'большинство из людей'},
    {id:207,eng:'sales',rus:'продажи'},
    {id:208,eng:'deep',rus:'глубокий'},
    {id:209,eng:'guide',rus:'руководство'},
    {id:210,eng:'involve',rus:'вовлекать, впутывать'},
    {id:211,eng:'nearly took',rus:'чуть не забрал'},
    {id:212,eng:'primary',rus:'начальный'},
    {id:213,eng:'core',rus:'основной'},
    {id:214,eng:'design',rus:'разработка'},
    {id:215,eng:'xxx',rus:'xxx'},
    {id:216,eng:'thing',rus:'вещь, предмет'},
    {id:217,eng:'perform',rus:'выполнять'},
    {id:218,eng:'queue',rus:'очередь'},
    {id:219,eng:'below',rus:'ниже'},
    {id:220,eng:'pass',rus:'передавать'},
    {id:221,eng:'reusable',rus:'переиспользуемый'},
    {id:222,eng:'similar',rus:'похожий'},
    {id:223,eng:'exist',rus:'существовать'},
    {id:224,eng:'xxx',rus:'xxx'},
    {id:225,eng:'list (глаг.)',rus:'перечислять'},
    {id:226,eng:'fit',rus:'соответствовать'},
    {id:227,eng:'flat',rus:'плоский, выровнять'},
    {id:228,eng:'common',rus:'обычный, общий'},
    {id:229,eng:'base',rus:'база, базовый'},
    {id:230,eng:'pull',rus:'тянуть на себя'},
    {id:231,eng:'second',rus:'второй'},
    {id:232,eng:'accept',rus:'принимать, согл-ться'},
    {id:233,eng:'restrict',rus:'ограничивать'},
    {id:234,eng:'That',rus:'этот'},
    {id:235,eng:'bring',rus:'приносить'},
    {id:236,eng:'multiple',rus:'несколько'},
    {id:237,eng:'throughout',rus:'на всем протяжении'},
    {id:238,eng:'foreign',rus:'иностранный'},
    {id:239,eng:'rate',rus:'оценивать'},
    {id:240,eng:'efficient',rus:'эффективный'},
    {id:241,eng:'query',rus:'запрос'},
    {id:242,eng:'nested',rus:'вложенный'},
    {id:243,eng:'spread',rus:'распространять'},
    {id:244,eng:'previous',rus:'предыдущий'},
    {id:245,eng:'Legacy',rus:'наследие'},
    {id:246,eng:'log statement',rus:'сообщение в журнале'},
    {id:247,eng:'avoid',rus:'избегать'},
    {id:248,eng:'process data',rus:'обрабатывать данные'},
    {id:249,eng:'therefore',rus:'следовательно'},
    {id:250,eng:'hack',rus:'взламывать'},
    {id:251,eng:'While',rus:'пока'},
    {id:252,eng:'prepare',rus:'подготовить'},
    {id:253,eng:'additional',rus:'дополнительный'},
    {id:254,eng:'like these',rus:'как это'},
    {id:255,eng:'intermediate',rus:'промежуточный'},
    {id:256,eng:'cumbersome',rus:'громоздкий'},
    {id:257,eng:'simplify',rus:'упрощать'},
    {id:258,eng:'reache',rus:'достигать'},
    {id:259,eng:'ability',rus:'способность'},
    {id:260,eng:'auth',rus:'авторизация'},
    {id:261,eng:'reminde',rus:'напоминать'},
    {id:262,eng:'access',rus:'доступ'},
    {id:263,eng:'determine',rus:'определять'},
    {id:264,eng:'ourselves',rus:'самостоятельно'},
    {id:265,eng:'look up',rus:'искать'},
    {id:266,eng:'lookup table',rus:'таблица поиска'},
    {id:267,eng:'loop',rus:'обработать в цикле'},
    {id:268,eng:'tap into',rus:'подключиться'},
    {id:269,eng:'stroke',rus:'инсульт'},
    {id:270,eng:'rather',rus:'раньше (скорее)'},
    {id:271,eng:'looking for',rus:'находясь в поиске'},
    {id:272,eng:'predefined',rus:'предопределенный'},
    {id:273,eng:'here',rus:'здесь'},
    {id:274,eng:'empty',rus:'пустой'},
    {id:275,eng:'wasted effort',rus:'напрасные усилия'},
    {id:276,eng:'dive',rus:'нырять'},
    {id:277,eng:'solve',rus:'решать'},
    {id:278,eng:'behind',rus:'позади'},
    {id:279,eng:'benefits',rus:'преимущества'},
    {id:280,eng:'utility',rus:'полезность'},
    {id:281,eng:'overwrite',rus:'перезаписывать'},
    {id:282,eng:'frequent',rus:'частый'},
    {id:283,eng:'themselves',rus:'сами себя'},
    {id:284,eng:'capabilities',rus:'возможности'},
    {id:285,eng:'explicit',rus:'явный'},
    {id:286,eng:'such',rus:'такой'},
    {id:287,eng:'expect',rus:'предвидеть'},
    {id:288,eng:'sense',rus:'смысл'},
    {id:289,eng:'condition',rus:'условие (задачи)'},
    {id:290,eng:'excerpt',rus:'отрывок, выписка'},
    {id:291,eng:'familiar',rus:'знакомый'},
    {id:292,eng:'directly',rus:'напрямую (движение)'},
    {id:293,eng:'whenever',rus:'всякий раз'},
    {id:294,eng:'by the time',rus:'к тому времени'},
    {id:295,eng:'screw',rus:'винт'},
    {id:296,eng:'ahead of time',rus:'досрочно'},
    {id:297,eng:'allow',rus:'позволять'},
    {id:298,eng:'statement',rus:'оператор'},
    {id:299,eng:'entities',rus:'сущности'},
    {id:300,eng:'equal',rus:'равный'},
    {id:301,eng:'behav',rus:'веcти себя'},
    {id:302,eng:'that make up',rus:'из которых состоит'},
    {id:303,eng:'approach',rus:'подход'},
    {id:304,eng:'ask',rus:'просить'},
    {id:305,eng:'feedback',rus:'обратная связь'},
    {id:306,eng:'above',rus:'выше по тексту'},
    {id:307,eng:'implicit',rus:'неявный'},
    {id:308,eng:'sequence',rus:'последовательность'},
    {id:309,eng:'rich',rus:'богатый'},
    {id:310,eng:'mean',rus:'означать, иметь ввиду'},
    {id:311,eng:'consumer',rus:'потребитель'},
    {id:312,eng:'within',rus:'в пределах'},
    {id:313,eng:'responsibilities',rus:'обязанности'},
    {id:314,eng:'recent',rus:'недавний'},
    {id:315,eng:'ххх',rus:'ххх'},
    {id:316,eng:'xxx',rus:'xxx'},
    {id:317,eng:'although',rus:'не смотря на то что'},
    {id:318,eng:'seem',rus:'казаться'},
    {id:319,eng:'supply',rus:'поставлять'},
    {id:320,eng:'until',rus:'до того как'},
    {id:321,eng:'notice',rus:'Обратите внимание'},
    {id:322,eng:'order',rus:'порядок'},
    {id:323,eng:'keep',rus:'содержать, хранить'},
    {id:324,eng:'in order',rus:'в целях'},
    {id:325,eng:'itself',rus:'сам'},
    {id:326,eng:'turns out',rus:'оказывается'},
    {id:327,eng:'same',rus:'такойже'},
    {id:328,eng:'outer',rus:'внешний'},
    {id:329,eng:'so far',rus:'до сих пор'},
    {id:330,eng:'кeep',rus:'держать'},
    {id:331,eng:'actually',rus:'фактически'},
    {id:332,eng:'compare',rus:'сравнивать'},
    {id:333,eng:'useful',rus:'полезный, функциональный'},
    {id:334,eng:'introduction',rus:'введение'},
    {id:335,eng:'especially',rus:'особенно'},
    {id:336,eng:'started off',rus:'начанались (зародились)'},
    {id:337,eng:'distribut',rus:'распределять'},
    {id:338,eng:'note',rus:'примечание'},
    {id:339,eng:'ххх',rus:'ххх'},
    {id:340,eng:'xxx',rus:'xxx'},
    {id:341,eng:'consider',rus:'рассматривать'},
    {id:342,eng:'define',rus:'определять переменную'},
    {id:343,eng:'order',rus:'заказывать'},
    {id:344,eng:'set up',rus:'настраивать, устанавливать'},
    {id:345,eng:'xxx',rus:'xxx'},
    {id:346,eng:'pending',rus:'в ожидании'},
    {id:347,eng:'role',rus:'роль'},
    {id:348,eng:'apparent',rus:'явный'},
    {id:349,eng:'prefer',rus:'предпочитать'},
    {id:350,eng:'compatibility',rus:'совместимость'},
    {id:351,eng:'assume',rus:'предполагать'},
    {id:352,eng:'become',rus:'становиться'},
    {id:353,eng:'receive',rus:'получать'},
    {id:354,eng:'appear',rus:'появляться'},
    {id:355,eng:'particular',rus:'частный, особый'},
    {id:356,eng:'сaveat',rus:'предостережение'},
    {id:357,eng:'along',rus:'вместе'},
    {id:358,eng:'ither',rus:'либо'},
    {id:359,eng:'assign',rus:'назначить'},
    {id:360,eng:'almost',rus:'почти'},
    {id:361,eng:'require',rus:'требовать'},
    {id:362,eng:'lack',rus:'недостаток'},
    {id:363,eng:'differ',rus:'отличаться'},
    {id:364,eng:'abusin',rus:'злоупотребление'},
    {id:365,eng:'xxx',rus:'xxx'},
    {id:366,eng:'manufacture',rus:'производство'},
    {id:367,eng:'ideation',rus:'идея'},
    {id:368,eng:'policies',rus:'политика'},
    {id:369,eng:'course',rus:'курс, процесс'},
    {id:370,eng:'wide',rus:'широкий'},
    {id:371,eng:'release',rus:'выпускать'},
    {id:372,eng:'interact',rus:'взаимодействовать'},
    {id:373,eng:'suggest',rus:'предлагать'},
    {id:374,eng:'prevent',rus:'предотвращать'},
    {id:375,eng:'mistake',rus:'ошибка'},
    {id:376,eng:'describe',rus:'описывать'},
    {id:377,eng:'occur',rus:'происходить'},
    {id:378,eng:'break down',rus:'авария, поломка'},
    {id:379,eng:'trigger',rus:'спусковой механизм'},
    {id:380,eng:'matter',rus:'иметь значение'},
    {id:381,eng:'enforcing rules',rus:'соблюдение правил'},
    {id:382,eng:'predict',rus:'предсказывать'},
    {id:383,eng:'amend',rus:'исправить'},
    {id:384,eng:'threshold',rus:'порог'},
    {id:385,eng:'checkout',rus:'проверить'},
    {id:386,eng:'cause',rus:'причина'},
    {id:387,eng:'commit',rus:'фиксировать'},
    {id:388,eng:'worry',rus:'волноваться'},
    {id:389,eng:'ensures',rus:'гарантирует'},
    {id:390,eng:'discard',rus:'отказаться'},
    {id:391,eng:'racial',rus:'рассовый'},
    {id:392,eng:'divide',rus:'разделять'},
    {id:393,eng:'leak',rus:'утечка'},
    {id:394,eng:'scores',rus:'баллы'},
    {id:395,eng:'resign',rus:'уйти в отставку'},
    {id:396,eng:'convers',rus:'беседовать'},
    {id:397,eng:'insult',rus:'оскорблять'},
    {id:398,eng:'slurs',rus:'оскорбления'},
    {id:399,eng:'deploy',rus:'развернуть'},
    {id:400,eng:'scratch',rus:'царапать'},
    {id:401,eng:'temporary',rus:'временный'},
    {id:402,eng:'match',rus:'соответствие, совподение'},
    {id:403,eng:'succss',rus:'успех'},
    {id:404,eng:'former',rus:'бывший'},
    {id:405,eng:'ease',rus:'простота'},
    {id:406,eng:'treasure',rus:'сокровищница'},
    {id:407,eng:'properly',rus:'правильно'},
    {id:408,eng:'accurate',rus:'точный'},
    {id:409,eng:'deliver',rus:'доставлять'},
    {id:410,eng:'follow',rus:'следовать, сопровождать'},
    {id:411,eng:'builtin',rus:'встроенный'},
    {id:412,eng:'evaluate',rus:'оценивать'},
    {id:413,eng:'goal',rus:'цель, задача, гол'},
    {id:414,eng:'establish',rus:'устанавливать, учреждать'},
    {id:415,eng:'convention',rus:'соглашение'},
    {id:416,eng:'reason',rus:'причина'},
    {id:417,eng:'environment',rus:'среда'},
    {id:418,eng:'duration',rus:'продолжительность'},
    {id:419,eng:'assert',rus:'утверждать'},
    {id:420,eng:'code',rus:'норма, код'},
    {id:421,eng:'сonduct',rus:'поведение, проводить'},
    {id:422,eng:'backer',rus:'сторонник, поддерживающий'},
    {id:423,eng:'dedicate',rus:'посвящать'},
    {id:424,eng:'exposure',rus:'экспозиция'},
    {id:425,eng:'upon',rus:'на'},
    {id:426,eng:'explain',rus:'объяснять'},
    {id:427,eng:'jest',rus:'шутка'},
    {id:428,eng:'various',rus:'различный'},
    {id:429,eng:'arise',rus:'возникать'},
    {id:430,eng:'resemble',rus:'быть похожим'},
    {id:431,eng:'confidenc',rus:'уверенность,  доверие'},
    {id:432,eng:'pure',rus:'чистый'},
    {id:433,eng:'dedicated',rus:'преданный (своему делу)'},
    {id:434,eng:'care',rus:'заботиться, забота'},
    {id:435,eng:'treated',rus:'отработанный (код)'},
    {id:436,eng:'circumstances',rus:'обстоятельства'},
    {id:437,eng:'widely',rus:'широко'},
    {id:438,eng:'pictorial',rus:'иллюстрированный'},
    {id:439,eng:'later',rus:'потом'},
    {id:440,eng:'poll',rus:'голосование, опрос'},
    {id:441,eng:'leading',rus:'лидирующий'},
    {id:442,eng:'ххх',rus:'ххх'},
    {id:443,eng:'ranked',rus:'ранжирован'},
    {id:444,eng:'assist',rus:'ассистировать, помогать'},
    {id:445,eng:'investigate',rus:'расследовать, исследвать'},
    {id:446,eng:'disaster',rus:'бедствие, катастрофа'},
    {id:447,eng:'credit',rus:'зачислять, кредитовать'},
    {id:448,eng:'held',rus:'держал'},
    {id:449,eng:'keen',rus:'увлеченный'},
    {id:450,eng:'both',rus:'оба'},
    {id:451,eng:'plenty',rus:'много'},
    {id:452,eng:'undergraduate',rus:'бакалавр'},
    {id:453,eng:'xxx',rus:'xxx'},
    {id:454,eng:'run',rus:'работать'},
    {id:455,eng:'scalable',rus:'масштабируемый'},
    {id:456,eng:'produce',rus:'производить'},
    {id:457,eng:'сonsequently',rus:'следовательно'},
    {id:458,eng:'unifyi',rus:'унифицироват, объединять'},
    {id:459,eng:'capable',rus:'способный'},
    {id:460,eng:'permit',rus:'разрешение, пропуск'},
    {id:461,eng:'other',rus:'другой'},
    {id:462,eng:'xxx',rus:'xxx'},
    {id:463,eng:'aim',rus:'цель, стремиться'},
    {id:464,eng:'throughput',rus:'пропускная способность'},
    {id:465,eng:'govern',rus:'управлять'},
    {id:466,eng:'facilitate',rus:'способствовать'},
    {id:467,eng:'serial',rus:'последовательный'},
    {id:468,eng:'mapping',rus:'отображение, сопоставление'},
    {id:469,eng:'exception',rus:'исключение, особая ситуация'},
    {id:470,eng:'feature-rich',rus:'многофункциональный'},
    {id:471,eng:'eventually',rus:'в итоге'},
    {id:472,eng:'upon first',rus:'после первого'},
    {id:473,eng:'yet',rus:'пока что'},
    {id:474,eng:'ххх',rus:'ххх'},
    {id:475,eng:'thus',rus:'таким образом'},
    {id:476,eng:'unit',rus:'блок'},
    {id:477,eng:'invoke',rus:'вызывать'},
    {id:478,eng:'capturing',rus:'перехват'},
    {id:479,eng:'mock',rus:'пародировать, высмеивать'},
    {id:480,eng:'proof',rus:'проверка, доказательство'},
    {id:481,eng:'ххх',rus:'ххх'},
    {id:482,eng:'unlike',rus:'в отличие'},
    {id:483,eng:'parties',rus:'стороны'},
    {id:484,eng:'consist',rus:'состоять'},
    {id:485,eng:'address',rus:'обращаться'},
    {id:486,eng:'vary',rus:'отличаться'},
    {id:487,eng:'retain',rus:'удерживать'},
    {id:488,eng:'serve',rus:'обслуживать'},
    {id:489,eng:'сomputer hardware',rus:'комп. железо'},
    {id:490,eng:'institute гл.',rus:'учреждать'},
    {id:491,eng:'device',rus:'устройство'},
    {id:492,eng:'runtimes',rus:'время выполнения'},
    {id:493,eng:'markup',rus:'разметка'},
    {id:494,eng:'disposal',rus:'утилизация'},
    {id:495,eng:'launch',rus:'запуск'},
    {id:496,eng:'challenging',rus:'сложный'},
    {id:497,eng:'decision',rus:'решение'},
    {id:498,eng:'cost',rus:'стоимость'},
    {id:499,eng:'mitigate',rus:'смягчать'},
    {id:500,eng:'encounter',rus:'сталкиваться'},
    {id:501,eng:'explore',rus:'исследовать'},
    {id:502,eng:'ххх',rus:'ххх'},
    {id:503,eng:'raw',rus:'сырой (проект)'},
    {id:504,eng:'proper',rus:'правильный'},
    {id:505,eng:'deadline',rus:'срок'},
    {id:506,eng:'unseen',rus:'невидимый'},
    {id:507,eng:'due',rus:'в связи'},
    {id:508,eng:'competitor',rus:'конкурент'},
    {id:509,eng:'influence',rus:'влияние'},
    {id:510,eng:'research',rus:'исследование'},
    {id:511,eng:'outstanding',rus:'выдающийся'},
    {id:512,eng:'tiny',rus:'крошечный'},
    {id:513,eng:'adhere',rus:'придерживаться'},
    {id:514,eng:'ххх',rus:'ххх'},
    {id:515,eng:'recognize',rus:'распознавать'},
    {id:516,eng:'guidelines',rus:'метод. рекомендации'},
    {id:517,eng:'constraint',rus:'ограничение'},
    {id:518,eng:'once ',rus:'как только'},
    {id:519,eng:'manner',rus:'манера, способ'},
    {id:520,eng:'broken',rus:'сломанный'},
    {id:521,eng:'discourage',rus:'обескуражить'},
    {id:522,eng:'draft',rus:'проект, черновик'},
    {id:523,eng:'explanation',rus:'объяснение, пример'},
    {id:524,eng:'ххх',rus:'ххх'},
    {id:525,eng:'outdated',rus:'устаревший'},
    {id:526,eng:'survey',rus:'опрос'},
    {id:527,eng:'gradual',rus:'посепенное'},
    {id:528,eng:'adoption',rus:'внедрение'},
    {id:529,eng:'whether',rus:'будь то'},
    {id:530,eng:'standalone',rus:'автономный'},
    {id:531,eng:'tab',rus:'вкладка'},
    {id:532,eng:'toolchain',rus:'набор инструментов'},
    {id:533,eng:'pleasant',rus:'приятный'},
    {id:534,eng:'experience',rus:'опыт'},
    {id:535,eng:'adventure',rus:'приключение'},
    {id:536,eng:'by breaking',rus:'разбив на'},
    {id:537,eng:'check out',rus:'ознакомтесь'},
    {id:538,eng:'advantage',rus:'преимущество'},
    {id:539,eng:'apart',rus:'отдельно'},
    {id:540,eng:'opinionated',rus:'самоуверенный'},
    {id:541,eng:'third-party',rus:'сторонний'},
    {id:542,eng:'compile',rus:'собирать'},
    {id:543,eng:'annotat',rus:'комментировать'},
    {id:544,eng:'bundle',rus:'связать'},
    {id:545,eng:'xxx',rus:'xxx'},
    {id:546,eng:'from scratch',rus:'с нуля'},
    {id:547,eng:'you might',rus:'ты можешь'},
    {id:548,eng:'right away',rus:'немедленно'},
    {id:549,eng:'xxx',rus:'xxx'},
    {id:550,eng:'xxx',rus:'xxx'},
    {id:551,eng:'plain',rus:'простой'},
    {id:552,eng:'belongs',rus:'принадлежит'},
    {id:553,eng:'otherwise',rus:'в противном случае'},
    {id:554,eng:'and so on',rus:'и так далее'},
    {id:555,eng:'remaining',rus:'осталось'},
    {id:556,eng:'boilerplate',rus:'шаблонный'},
    {id:557,eng:'straight',rus:'прямой, простой'},
    {id:558,eng:'pipeline',rus:'конвейер'},
    {id:559,eng:'omit',rus:'пропускать'},
    {id:560,eng:'derive',rus:'извлекать'},
    {id:561,eng:'though',rus:'хотя'},
    {id:562,eng:'less',rus:'меньше'},
    {id:563,eng:'greater',rus:'больше'},
    {id:564,eng:'adjust',rus:'регулировать'},
    {id:565,eng:'pair',rus:'сравнение, пара'},
    {id:566,eng:'exact',rus:'точный'},
    {id:567,eng:'distinguish',rus:'выделть, различать'},
    {id:568,eng:'precise',rus:'точный'},
    {id:569,eng:'corresponds',rus:'соответствует'},
    {id:570,eng:'against',rus:'против'},
    {id:571,eng:'throw',rus:'бросать'},
    {id:572,eng:'suppose',rus:'предполагать'},
    {id:573,eng:'butter',rus:'масло'},
    {id:574,eng:'intend',rus:'намереваться'},
    {id:575,eng:'soon',rus:'скоро'},
    {id:576,eng:'happen',rus:'случится, произойдет'},
    {id:577,eng:'would',rus:'бы'},
    {id:578,eng:'bothersome ',rus:'надоедливый'},
    {id:579,eng:'imagine',rus:'представим'},
    {id:580,eng:'inject',rus:'вводить, впрыскивать'},
    {id:581,eng:'hitting ',rus:'обращение к'},
    {id:582,eng:'fragile',rus:'хрупкий'},
    {id:583,eng:'subset',rus:'подмножество'},
    {id:584,eng:'beyond',rus:'вне'},
    {id:585,eng:'Broadly',rus:'широко'},
    {id:586,eng:'on top of',rus:'на основе'},
    {id:587,eng:'encourages',rus:'поощряет'},
    {id:588,eng:'better',rus:'лучше'},
    {id:589,eng:'expose',rus:'раскрывать'},
    {id:590,eng:'escape',rus:'побег'},
    {id:591,eng:'miss',rus:'скучать, пропускать'},
    {id:592,eng:'xxx',rus:'xxx'},
    {id:593,eng:'run closer',rus:'более приближенные'},
    {id:594,eng:'hatch',rus:'люк'},
    {id:595,eng:'dummy',rus:'макет, болван'},
    {id:596,eng:'flake',rus:'отслаиваться'},
    {id:597,eng:'even',rus:'даже'},
    {id:598,eng:'arrange',rus:'Договариваться'},
    {id:599,eng:'alert',rus:'сигнал тревоги'},
    {id:600,eng:'affect',rus:'оказывать воздействие'},
    {id:601,eng:'appropriate',rus:'соответствующий'},
    {id:602,eng:'external',rus:'внешний'},
    {id:603,eng:'subsequent',rus:'последующий'},
    {id:604,eng:'either',rus:'либо'},
    {id:605,eng:'patter',rus:'скороговорка'},
    {id:606,eng:'tighter',rus:'тесный'},
    {id:607,eng:'xxx',rus:'xxx'},
    {id:608,eng:'boon',rus:'благо'},
    {id:609,eng:'layer',rus:'слой'},
    {id:610,eng:'hood',rus:'капот'},
    {id:611,eng:'infer',rus:'делать вывод, предпологать'},
    {id:612,eng:'conform',rus:'соответствовать'},
    {id:613,eng:'since',rus:'союз'},
    {id:614,eng:'annotate',rus:'комментировать'},
    {id:615,eng:'union',rus:'распознавать'},
    {id:616,eng:'generic',rus:'общий'},
    {id:617,eng:'shortcut',rus:'ярлык'},
    {id:618,eng:'backpack ',rus:'рюкзак'},
    {id:619,eng:'suite',rus:'набор (set)'},
    {id:620,eng:'specify',rus:'указать'},
    {id:621,eng:'probably',rus:'наверное'},
    {id:622,eng:'purpose',rus:'цель'},
    {id:623,eng:'sanitize',rus:'дезинфицировать'},
    {id:624,eng:'figure out',rus:'выяснять, понять'},
    {id:625,eng:'to force',rus:'заставить'},
    {id:626,eng:'trial',rus:'пробный'},
    {id:627,eng:'worth',rus:'ценный'},
    {id:628,eng:'convenience',rus:'удобство'},
    {id:629,eng:'hence',rus:'следовательно'},
    {id:630,eng:'mostly',rus:'главным образом'},
    {id:631,eng:'missing',rus:'недостающий'},
    {id:632,eng:'sign up',rus:'зарегистрироваться'},
    {id:633,eng:'expand',rus:'расширять'},
    {id:634,eng:'accidental',rus:'случайный'},
    {id:635,eng:'eliminate',rus:'устранять'},
    {id:636,eng:'Tip',rus:'совет'},
    {id:637,eng:'couple',rus:'пара'},
    {id:638,eng:'permits',rus:'разрешает'},
    {id:639,eng:'accident',rus:'несчастный случай'},
    {id:640,eng:'lead',rus:'привести'},
    {id:641,eng:'getting lost',rus:'потеряться'},
    {id:642,eng:'occasionally',rus:'изредка'},
    {id:643,eng:'sprinkles',rus:'посыпать (немного добавить)'},
    {id:644,eng:'spot',rus:'место'},
    {id:645,eng:'place',rus:'разместить'},
    {id:646,eng:'right before',rus:'прямо перед'},
    {id:647,eng:'pitfall',rus:'ловушка'},
    {id:648,eng:'lastly',rus:'наконец'},
    {id:649,eng:'congratulate',rus:'поздравлять'},
    {id:650,eng:'suite',rus:'набор'},
    {id:651,eng:'precautionary',rus:'предупредительный'},
    {id:652,eng:'prone',rus:'склонный'},
    {id:653,eng:'safe',rus:'безопасно'},
    {id:654,eng:'moreover',rus:'более того'},
    {id:655,eng:'frustrate',rus:'расстроить, раздражать'},
    {id:656,eng:'since',rus:'поскольку'},
    {id:657,eng:'substitute',rus:'заменять'},
    {id:658,eng:'worth noting',rus:'стоит отметить'},
    {id:659,eng:'confus',rus:'путать'},
    {id:660,eng:'messy',rus:'грязный'},
    {id:661,eng:'ambient',rus:'окружающий'},
    {id:662,eng:'slightly',rus:'немного'},
    {id:663,eng:'unless',rus:'пока не'},
    {id:664,eng:'bypass',rus:'обходить'},
    {id:665,eng:'elsewhere',rus:'где-то еще'},
    {id:666,eng:'wealth',rus:'изобилие, богатство'},
    {id:667,eng:'to face',rus:'сталкиваться'},
    {id:668,eng:'once',rus:'один раз'},
    {id:669,eng:'complement',rus:'дополнять'},
    {id:670,eng:'knowledge',rus:'знания'},
    {id:671,eng:'suite',rus:'набор'},
    {id:672,eng:'accord',rus:'согласие'},
    {id:673,eng:'ххх',rus:'ххх'},
    {id:674,eng:'rely',rus:'полагаться'},
]