
export const data = [
    {id:1,eng:'implement',rus:'реализовывать'}, 
    {id:2,eng:'select',rus:'выбирать'},
    {id:3,eng:'advance',rus:'продвигать'},
    {id:4,eng:'certain',rus:'определенный'},
    {id:5,eng:'necessary',rus:'необходимый'},
    {id:6,eng:'flow',rus:'поток'},
    {id:7,eng:'opacity',rus:'непрозрачность'},
    {id:8,eng:'template',rus:'шаблон'},
    {id:9,eng:'override',rus:'обойти сист. без.'},
    {id:10,eng:'preserve',rus:'защищать'},
    {id:11,eng:'drop',rus:'уронить'},
    {id:12,eng:'usage',rus:'использование'},
    {id:13,eng:'nut',rus:'гайка'},
    {id:14,eng:'scope',rus:'масштаб охвата'},
    {id:15,eng:'bolt',rus:'болт'},
    {id:16,eng:'edit',rus:'редактировать'},
    {id:17,eng:'during',rus:'в течение'},
    {id:18,eng:'snap',rus:'клик'},
    {id:19,eng:'thread',rus:'резьба'},
    {id:20,eng:'network',rus:'сеть'},
    {id:21,eng:'plug',rus:'затыкать'},
    {id:22,eng:'latest',rus:'последний'},
    {id:23,eng:'able',rus:'способный'},
    {id:24,eng:'trip',rus:'путешествие'},
    {id:25,eng:'deal',rus:'иметь дело'},
    {id:26,eng:'tradeoff',rus:'компромисc'},
    {id:27,eng:'indirect',rus:'косвенный'},
    {id:28,eng:'short term',rus:'краткосрочный'},
    {id:29,eng:'might',rus:'мочь, мощь'},
    {id:30,eng:'decide',rus:'решать'},
    {id:31,eng:'sure',rus:'уверенн, конечно'},
    {id:32,eng:'choice',rus:'выбор'},
    {id:33,eng:'intent',rus:'намерение/цель'},
    {id:34,eng:'buy',rus:'купить'},
    {id:35,eng:'margin',rus:'поле (отступ внешний)'},
    {id:36,eng:'flex',rus:'сгибаться'},
    {id:37,eng:'grass',rus:'трава'},
    {id:38,eng:'where',rus:'куда, где'},
    {id:39,eng:'summary',rus:'резюме, заключение'},
    {id:40,eng:'to',rus:'к'},
    {id:41,eng:'enough',rus:'достаточно'},
    {id:42,eng:'generally',rus:'в главном'},
    {id:43,eng:'brief retelling',rus:'краткий пересказ'},
    {id:44,eng:'independence',rus:'не-зависимость'},
    {id:45,eng:'response ',rus:'отклик'},
    {id:46,eng:'hid',rus:'спрятать'},
    {id:47,eng:'seize',rus:'захватывать'},
    {id:48,eng:'snippets',rus:'фрагменты'},
    {id:49,eng:'middle',rus:'середина'},
    {id:50,eng:'switch',rus:'выключатель'},
    {id:51,eng:'several',rus:'несколько'},
    {id:52,eng:'wheel',rus:'рулевое колесо'},
    {id:53,eng:'sources',rus:'источники'},
    {id:54,eng:'viewport',rus:'окно простмотра'},
    {id:55,eng:'adjacent',rus:'сосед '},
    {id:56,eng:'application',rus:'приложение-программа'},
    {id:57,eng:'lighthouse',rus:'маяк'},
    {id:58,eng:'recorder',rus:'регистратор, магнитофон'},
    {id:59,eng:'align',rus:'выровнять (текст)'},
    {id:60,eng:'overview',rus:'обзор'},
    {id:61,eng:'drag',rus:'тащить'},
    {id:62,eng:'performance',rus:'производительность'},
    {id:63,eng:'since',rus:'с'},
    {id:64,eng:'host',rus:'хозяин'},
    {id:65,eng:'anyone',rus:'кто угодно'},
    {id:66,eng:'heap',rus:'куча'},
    {id:67,eng:'few',rus:'несколько'},
    {id:68,eng:'redirect',rus:'перенаправить'},
    {id:69,eng:'through',rus:'через, поперек'},
    {id:70,eng:'background ',rus:'фон'},
    {id:71,eng:'still ',rus:'всё ещё'},
    {id:72,eng:'pretty small',rus:'довольно маленький'},
    {id:73,eng:'task',rus:'задача, задание'},
    {id:74,eng:'provide',rus:'предоставлять'},
    {id:75,eng:'lot',rus:'много'},
    {id:76,eng:'plugin',rus:'вставной'},
    {id:77,eng:'request',rus:'запрос'},
    {id:78,eng:'strange',rus:'странный'},
    {id:79,eng:'enqueue',rus:'поставить в очередь'},
    {id:80,eng:'share',rus:'поделиться, открыть доступ'},
    {id:81,eng:'verbose',rus:'многословный'},
    {id:82,eng:'hold',rus:'держать'},
    {id:83,eng:'overflow',rus:'переполнение'},
    {id:84,eng:'display',rus:'экран'},
    {id:85,eng:'sign',rus:'знак'},
    {id:86,eng:'via',rus:'с помощью'},
    {id:87,eng:'apply',rus:'применять'},
    {id:88,eng:'ink',rus:'чернила'},
    {id:89,eng:'signature',rus:'подпись'},
    {id:90,eng:'there',rus:'там'},
    {id:91,eng:'disable',rus:'отключить'},
    {id:92,eng:'shape',rus:'форма, формировать'},
    {id:93,eng:'in recent years',rus:'в недавние (последние) годы'},
    {id:94,eng:'background',rus:'происхождение (история)'},
    {id:95,eng:'vitals',rus:'жизнено важные органы'},
    {id:96,eng:'pan',rus:'лоток, кастрюля, протвень,'},
    {id:97,eng:'snapshot',rus:'снимок'},
    {id:98,eng:'among',rus:'среди'},
    {id:99,eng:'rest',rus:'остаток, отдых'},
    {id:100,eng:'select',rus:'выбирать'},
    {id:101,eng:'strengyhen',rus:'укреплять, усиливать'},
    {id:102,eng:'relate',rus:'относится, связывать'},
    {id:103,eng:'highlight',rus:'важный момент (выделенный-ть)'},
    {id:104,eng:'early days',rus:'в первые дни, изначально'},
    {id:105,eng:'attach',rus:'прикладывать, прикреплять'},
    {id:106,eng:'was to do',rus:'были сделаны'},
    {id:107,eng:'complete',rus:'полностью законченный'},
    {id:108,eng:'issues',rus:'спорный вопрос'},
    {id:109,eng:'increase',rus:'увеличение'},
    {id:110,eng:'display',rus:'отображать'},
    {id:111,eng:'popup',rus:'всплывающий, выскакивающий'},
    {id:112,eng:'momentum',rus:'момент'},
    {id:113,eng:'pricing',rus:'ценообразование'},
    {id:114,eng:'capitalize',rus:'извлекать выгоду'},
    {id:115,eng:'strong',rus:'крепкий'},
    {id:116,eng:'resolve a dispute',rus:'разрешить спор (разобрать)'},
    {id:117,eng:'along',rus:'вдоль'},
    {id:118,eng:'which',rus:'который, какой, что'},
    {id:119,eng:'ribbon',rus:'лента'},
    {id:120,eng:'ceiling',rus:'потолок'},
    {id:121,eng:'entire',rus:'весь, полностью'},
    {id:122,eng:'choose',rus:'выбирать'},
    {id:123,eng:'subscriber',rus:'подписчик'},
    {id:124,eng:'remote',rus:'удаленный, дистанционный'},
    {id:125,eng:'believe',rus:'верить'},
    {id:126,eng:'bookmark',rus:'закладка в книге'},
    {id:127,eng:'eraser',rus:'ластик'},
    {id:128,eng:'case',rus:'ситуация, случай'},
    {id:129,eng:'health',rus:'здоровье'},
    {id:130,eng:'chair',rus:'стул'},
    {id:131,eng:'attachment',rus:'вложение, приложение'},
    {id:132,eng:'fork',rus:'вилка'},
    {id:133,eng:'hear',rus:'слышать'},
    {id:134,eng:'advance',rus:'продвигать'},
    {id:135,eng:'leave',rus:'покидать'},
    {id:136,eng:'ask',rus:'спрашивать'},
    {id:137,eng:'turn',rus:'поворачивать'},
    {id:138,eng:'actions',rus:'действия'},
    {id:139,eng:'available',rus:'доступный'},
    {id:140,eng:'late',rus:'поздний'},
    {id:141,eng:'wrong',rus:'неправильный, неверный'},
    {id:142,eng:'rectangle',rus:'прямоугольник'},
    {id:143,eng:'whole',rus:'весь'},
    {id:144,eng:'collaborate',rus:'сотрудничать'},
    {id:145,eng:'sensitive',rus:'чувствительный'},
    {id:146,eng:'poor',rus:'бедняк, бедный'},
    {id:147,eng:'cloud',rus:'облако'},
    {id:148,eng:'vertex',rus:'вершина'},
    {id:149,eng:'tutorial',rus:'руководство'},
    {id:150,eng:'forward',rus:'вперед'},
    {id:151,eng:'measure',rus:'измерять'},
    {id:152,eng:'enterprise',rus:'предприятие'},
    {id:153,eng:'software',rus:'ПО'},
    {id:154,eng:'hidden',rus:'скрытый'},
    {id:155,eng:'view',rus:'вид'},
    {id:156,eng:'ship',rus:'судно'},
    {id:157,eng:'education',rus:'образование'},
    {id:158,eng:'include',rus:'включая'},
    {id:159,eng:'detailed',rus:'детализированный, подробный'},
    {id:160,eng:'dispatch',rus:'отправка'},
    {id:161,eng:'handl',rus:'обрабатывать'},
    {id:162,eng:'offere',rus:'предложение'},
    {id:163,eng:'hub',rus:'центр деятельности'},
    {id:164,eng:'feature',rus:'особенность, штуковина'},
    {id:165,eng:'prerequisites',rus:'предпосылки'},
    {id:166,eng:'customize',rus:'настроить'},
    {id:167,eng:'enable',rus:'включить, дать возможность'},
    {id:168,eng:'demand',rus:'требовать'},
    {id:169,eng:'pieces',rus:'части'},
    {id:170,eng:'wonder',rus:'удивление, чудо'},
    {id:171,eng:'essential',rus:'основы'},
    {id:172,eng:'salary',rus:'зарплата'},
    {id:173,eng:'layout',rus:'макет'},
    {id:174,eng:'might',rus:'сила, мощь'},
    {id:175,eng:'look like',rus:'быть похожим '},
    {id:176,eng:'should',rus:'должен'},
    {id:177,eng:'own',rus:'свой собственный'},
    {id:178,eng:'feed',rus:'поток скармливаемой информации'},
    {id:179,eng:'split',rus:'расколоть на части'},
    {id:180,eng:'native',rus:'натуральный, естественный'},
    {id:181,eng:'side',rus:'сторона, бок'},
    {id:182,eng:'basic',rus:'базовый'},
    {id:183,eng:'extra',rus:'дополнительный'},
    {id:184,eng:'could',rus:'мог'},
    {id:185,eng:'entrie',rus:'вход'},
    {id:186,eng:'chapter',rus:'глава'},
    {id:187,eng:'improve',rus:'улучшать'},
    {id:188,eng:'concurrency',rus:'параллелизм'},
    {id:189,eng:'instead',rus:'вместо, взамен'},
    {id:190,eng:'let',rus:'позволять, допускать'},
    {id:191,eng:'however',rus:'однако'},
    {id:192,eng:'their',rus:'их'},
    {id:193,eng:'case sensitive',rus:'с учетом регистра'},
    {id:194,eng:'maintain',rus:'поддерживать'},
    {id:195,eng:'implement',rus:'реализовть'},
    {id:196,eng:'government',rus:'правительство'},
    {id:197,eng:'rules',rus:'правила'},
    {id:198,eng:'pane',rus:'панель'},
    {id:199,eng:'bit',rus:'немного'},

]
