








export const data = [
    {id:1,eng:'implement',rus:'реализовывать'}, 
    {id:2,eng:'select',rus:'выбирать'},
    {id:3,eng:'advance',rus:'продвигать'},
    {id:4,eng:'certain',rus:'определенный'},
    {id:5,eng:'necessary',rus:'необходимый'},
    {id:6,eng:'flow',rus:'поток'},
    {id:7,eng:'opacity',rus:'непрозрачность'},
    {id:8,eng:'template',rus:'шаблон'},
    {id:9,eng:'override',rus:'обойти сист. без.'},
    {id:10,eng:'preserve',rus:'защищать'},
    {id:11,eng:'drop',rus:'уронить'},
    {id:12,eng:'usage',rus:'использование'},
    {id:13,eng:'nut',rus:'гайка'},
    {id:14,eng:'scope',rus:'масштаб охвата'},
    {id:15,eng:'bolt',rus:'болт'},
    {id:16,eng:'edit',rus:'редактировать'},
    {id:17,eng:'during',rus:'в течение'},
    {id:18,eng:'snap',rus:'клик'},
    {id:19,eng:'thread',rus:'резьба'},
    {id:20,eng:'network',rus:'сеть'},
    {id:21,eng:'plug',rus:'затыкать'},
    {id:22,eng:'latest',rus:'последний'},
    {id:23,eng:'able',rus:'способный'},
    {id:24,eng:'trip',rus:'путешествие'},
    {id:25,eng:'deal',rus:'иметь дело'},
    {id:26,eng:'tradeoff',rus:'компромисc'},
    {id:27,eng:'indirect',rus:'косвенный'},
    {id:28,eng:'short term',rus:'краткосрочный'},
    {id:29,eng:'might',rus:'мочь, мощь'},
    {id:30,eng:'decide',rus:'решать'},
    {id:31,eng:'sure',rus:'уверенн, конечно'},
    {id:32,eng:'choice',rus:'выбор'},
    {id:33,eng:'intent',rus:'цель'},
    {id:34,eng:'buy',rus:'купить'},
    {id:35,eng:'margin',rus:'поле (отступ внешний)'},
    {id:36,eng:'flex',rus:'сгибаться'},
    {id:37,eng:'grass',rus:'трава'},
    {id:38,eng:'where',rus:'куда, где'},
    {id:39,eng:'summary',rus:'резюме, заключение'},
    {id:40,eng:'to',rus:'к'},
    {id:41,eng:'enough',rus:'достаточно'},
    {id:42,eng:'generally',rus:'в главном'},
    {id:43,eng:'brief retelling',rus:'краткий пересказ'},
    {id:44,eng:'independence',rus:'независимость'},
    {id:45,eng:'response ',rus:'отклик'},
    {id:46,eng:'hid',rus:'спрятать'},
    {id:47,eng:'seize',rus:'захватывать'},
    {id:48,eng:'snippets',rus:'фрагменты'},
    {id:49,eng:'middle',rus:'середина'},
    {id:50,eng:'switch',rus:'выключатель'},
    {id:51,eng:'several',rus:'несколько'},
    {id:52,eng:'wheel',rus:'рулевое колесо'},
    {id:53,eng:'sources',rus:'источники'},
    {id:54,eng:'viewport',rus:'окно простмотра'},
    {id:55,eng:'adjacent',rus:'сосед '},
    {id:56,eng:'application',rus:'приложение'},
    {id:57,eng:'lighthouse',rus:'маяк'},
    {id:58,eng:'recorder',rus:'регистратор, магнитофон'},
    {id:59,eng:'align',rus:'выровнять (текст)'},
    {id:60,eng:'overview',rus:'обзор'},
    {id:61,eng:'drag',rus:'тащить'},
    {id:62,eng:'performance',rus:'производительность'},
    {id:63,eng:'since',rus:'с'},
    {id:64,eng:'host',rus:'хозяин'},
    {id:65,eng:'anyone',rus:'кто угодно'},
    {id:66,eng:'heap',rus:'куча'},
    {id:67,eng:'few',rus:'несколько'},
    {id:68,eng:'redirect',rus:'перенаправить'},
    {id:69,eng:'through',rus:'через, поперек'},
    {id:70,eng:'background ',rus:'фон'},
    {id:71,eng:'still ',rus:'всё ещё'},
    {id:72,eng:'pretty small',rus:'довольно маленький'},
    {id:73,eng:'task',rus:'задача, задание'},
    {id:74,eng:'provide',rus:'предоставлять'},
    {id:75,eng:'lot',rus:'много'},
    {id:76,eng:'plugin',rus:'вставной'},
    {id:77,eng:'request',rus:'запрос'},
    {id:78,eng:'strange',rus:'странный'},
    {id:79,eng:'enqueue',rus:'поставить в очередь'},
    {id:80,eng:'share',rus:'поделиться доступом'},
    {id:81,eng:'verbose',rus:'многословный'},
    {id:82,eng:'hold',rus:'держать'},
    {id:83,eng:'overflow',rus:'переполнение'},
    {id:84,eng:'display',rus:'экран'},
    {id:85,eng:'sign',rus:'знак'},
    {id:86,eng:'via',rus:'с помощью'},
    {id:87,eng:'apply',rus:'применять'},
    {id:88,eng:'ink',rus:'чернила'},
    {id:89,eng:'signature',rus:'подпись'},
    {id:90,eng:'there',rus:'там'},
    {id:91,eng:'disable',rus:'отключить'},
    {id:92,eng:'shape',rus:'форма, формировать'},
    {id:93,eng:'in recent years',rus:'в недавние годы'},
    {id:94,eng:'background',rus:'происхождение, история'},
    {id:95,eng:'vitals',rus:'жизнено важные органы'},
    {id:96,eng:'pan',rus:'лоток, кастрюля, протвень,'},
    {id:97,eng:'snapshot',rus:'снимок'},
    {id:98,eng:'among',rus:'среди'},
    {id:99,eng:'rest',rus:'остаток, отдых'},
    {id:100,eng:'select',rus:'выбирать'},
    {id:101,eng:'strengyhen',rus:'укреплять, усиливать'},
    {id:102,eng:'relate',rus:'относится, связывать'},
    {id:103,eng:'highlight',rus:'важный момент (выделенный)'},
    {id:104,eng:'early days',rus:'в первые дни, изначально'},
    {id:105,eng:'attach',rus:'прикладывать, прикреплять'},
    {id:106,eng:'was to do',rus:'были сделаны'},
    {id:107,eng:'complete',rus:'полностью законченный'},
    {id:108,eng:'issues',rus:'спорный вопрос'},
    {id:109,eng:'increase',rus:'увеличение'},
    {id:110,eng:'display',rus:'отображать'},
    {id:111,eng:'popup',rus:'всплывающий, выскакивающий'},
    {id:112,eng:'momentum',rus:'момент'},
    {id:113,eng:'pricing',rus:'ценообразование'},
    {id:114,eng:'capitalize',rus:'извлекать выгоду'},
    {id:115,eng:'strong',rus:'крепкий'},
    {id:116,eng:'resolve a dispute',rus:'разрешить спор (разобрать)'},
    {id:117,eng:'along',rus:'вдоль'},
    {id:118,eng:'which',rus:'который, какой, что'},
    {id:119,eng:'ribbon',rus:'лента'},
    {id:120,eng:'ceiling',rus:'потолок'},
    {id:121,eng:'entire',rus:'весь, полностью'},
    {id:122,eng:'choose',rus:'выбирать'},
    {id:123,eng:'subscriber',rus:'подписчик'},
    {id:124,eng:'remote',rus:'удаленный, дистанционный'},
    {id:125,eng:'believe',rus:'верить'},
    {id:126,eng:'bookmark',rus:'закладка в книге'},
    {id:127,eng:'eraser',rus:'ластик'},
    {id:128,eng:'case',rus:'ситуация, случай'},
    {id:129,eng:'health',rus:'здоровье'},
    {id:130,eng:'chair',rus:'стул'},
    {id:131,eng:'attachment',rus:'вложение, приложение'},
    {id:132,eng:'fork',rus:'вилка'},
    {id:133,eng:'hear',rus:'слышать'},
    {id:134,eng:'advance',rus:'продвигать'},
    {id:135,eng:'leave',rus:'покидать'},
    {id:136,eng:'ask',rus:'спрашивать'},
    {id:137,eng:'turn',rus:'поворачивать'},
    {id:138,eng:'actions',rus:'действия'},
    {id:139,eng:'available',rus:'доступный'},
    {id:140,eng:'late',rus:'поздний'},
    {id:141,eng:'wrong',rus:'неправильный, неверный'},
    {id:142,eng:'rectangle',rus:'прямоугольник'},
    {id:143,eng:'whole',rus:'весь'},
    {id:144,eng:'collaborate',rus:'сотрудничать'},
    {id:145,eng:'sensitive',rus:'чувствительный'},
    {id:146,eng:'poor',rus:'бедняк, бедный'},
    {id:147,eng:'cloud',rus:'облако'},
    {id:148,eng:'vertex',rus:'вершина'},
    {id:149,eng:'tutorial',rus:'руководство'},
    {id:150,eng:'forward',rus:'вперед'},
    {id:151,eng:'measure',rus:'измерять'},
    {id:152,eng:'enterprise',rus:'предприятие'},
    {id:153,eng:'software',rus:'ПО'},
    {id:154,eng:'hidden',rus:'скрытый'},
    {id:155,eng:'view',rus:'вид'},
    {id:156,eng:'ship',rus:'судно'},
    {id:157,eng:'education',rus:'образование'},
    {id:158,eng:'include',rus:'включая'},
    {id:159,eng:'detailed',rus:'детализированный, подробный'},
    {id:160,eng:'dispatch',rus:'отправка'},
    {id:161,eng:'handl',rus:'обрабатывать'},
    {id:162,eng:'offere',rus:'предложение'},
    {id:163,eng:'hub',rus:'центр деятельности'},
    {id:164,eng:'feature',rus:'особенность, штуковина'},
    {id:165,eng:'prerequisites',rus:'предпосылки'},
    {id:166,eng:'customize',rus:'настроить'},
    {id:167,eng:'enable',rus:'включить, дать возможность'},
    {id:168,eng:'demand',rus:'требовать'},
    {id:169,eng:'pieces',rus:'части'},
    {id:170,eng:'wonder',rus:'удивление, чудо'},
    {id:171,eng:'essential',rus:'основы'},
    {id:172,eng:'salary',rus:'зарплата'},
    {id:173,eng:'layout',rus:'макет'},
    {id:174,eng:'might',rus:'сила, мощь'},
    {id:175,eng:'look like',rus:'быть похожим '},
    {id:176,eng:'should',rus:'должен'},
    {id:177,eng:'own',rus:'свой собственный'},
    {id:178,eng:'feed',rus:'поток скармливаемой информации'},
    {id:179,eng:'split',rus:'расколоть на части'},
    {id:180,eng:'native',rus:'натуральный, естественный'},
    {id:181,eng:'side',rus:'сторона, бок'},
    {id:182,eng:'basic',rus:'базовый'},
    {id:183,eng:'extra',rus:'дополнительный'},
    {id:184,eng:'could',rus:'мог'},
    {id:185,eng:'entrie',rus:'вход'},
    {id:186,eng:'chapter',rus:'глава'},
    {id:187,eng:'improve',rus:'улучшать'},
    {id:188,eng:'concurrency',rus:'параллелизм'},
    {id:189,eng:'instead',rus:'вместо, взамен'},
    {id:190,eng:'let',rus:'позволять, допускать'},
    {id:191,eng:'however',rus:'однако'},
    {id:192,eng:'their',rus:'их'},
    {id:193,eng:'case sensitive',rus:'с учетом регистра'},
    {id:194,eng:'maintain',rus:'поддерживать'},
    {id:195,eng:'implement',rus:'реализовть'},
    {id:196,eng:'government',rus:'правительство'},
    {id:197,eng:'rules',rus:'правила'},
    {id:198,eng:'pane',rus:'панель'},
    {id:199,eng:'bit',rus:'немного'},
    {id:200,eng:'select',rus:'выбирать'},
    {id:201,eng:'link',rus:'связь, связать'},
    {id:202,eng:'as well	as',rus:'а также'},
    {id:203,eng:'arrow',rus:'стрелка'},
    {id:204,eng:'fast forward',rus:'промотаем время вперед'},
    {id:205,eng:'so',rus:'таким оброзом'},
    {id:206,eng:'most of the people',rus:'большинство из людей'},
    {id:207,eng:'sales',rus:'продажи'},
    {id:208,eng:'deep',rus:'глубокий'},
    {id:209,eng:'guide',rus:'руководство'},
    {id:210,eng:'involve',rus:'вовлекать, впутывать'},
    {id:211,eng:'nearly took',rus:'чуть не забрал'},
    {id:212,eng:'primary',rus:'начальный'},
    {id:213,eng:'core',rus:'основной'},
    {id:214,eng:'design',rus:'разработка'},
    {id:215,eng:'basic',rus:'базовый'},
    {id:216,eng:'thing',rus:'вещь, предмет'},
    {id:217,eng:'perform',rus:'выполнять'},
    {id:218,eng:'queue',rus:'очередь'},
    {id:219,eng:'below',rus:'ниже'},
    {id:220,eng:'pass',rus:'передавать'},
    {id:221,eng:'reusable',rus:'переиспользуемый'},
    {id:222,eng:'similar',rus:'похожий'},
    {id:223,eng:'exist',rus:'существовать'},
    {id:224,eng:'certain',rus:'определенный'},
    {id:225,eng:'list (глаг.)',rus:'перечислять'},
    {id:226,eng:'fit',rus:'соответствовать'},
    {id:227,eng:'flat',rus:'плоский, выровнять'},
    {id:228,eng:'common',rus:'обычный, общий'},
    {id:229,eng:'base',rus:'база, базовый'},
    {id:230,eng:'pull',rus:'тянуть на себя'},
    {id:231,eng:'second',rus:'второй'},
    {id:232,eng:'accept',rus:'принимать, согл-ться'},
    {id:233,eng:'restrict',rus:'ограничивать'},
    {id:234,eng:'That',rus:'этот'},
    {id:235,eng:'bring',rus:'приносить'},
    {id:236,eng:'multiple',rus:'несколько'},
    {id:237,eng:'throughout',rus:'на всем протяжении'},
    {id:238,eng:'foreign',rus:'иностранный'},
    {id:239,eng:'rate',rus:'оценивать'},
    {id:240,eng:'efficient',rus:'эффективный'},
    {id:241,eng:'query',rus:'запрос'},
    {id:242,eng:'nested',rus:'вложенный'},
    {id:243,eng:'spread',rus:'распространять'},
    {id:244,eng:'previous',rus:'предыдущий'},
    {id:245,eng:'Legacy',rus:'наследие'},
    {id:246,eng:'log statement',rus:'сообщение в журнале'},
    {id:247,eng:'avoid',rus:'избегать'},
    {id:248,eng:'process data',rus:'обрабатывать данные'},
    {id:249,eng:'therefore',rus:'следовательно'},
    {id:250,eng:'hack',rus:'взламывать'},
    {id:251,eng:'While',rus:'пока'},
    {id:252,eng:'prepare',rus:'подготовить'},
    {id:253,eng:'additional',rus:'дополнительный'},
    {id:254,eng:'like these',rus:'как это'},
    {id:255,eng:'intermediate',rus:'промежуточный'},
    {id:256,eng:'cumbersome',rus:'громоздкий'},
    {id:257,eng:'simplify',rus:'упрощать'},
    {id:258,eng:'reache',rus:'достигать'},
    {id:259,eng:'ability',rus:'способность'},
    {id:260,eng:'auth',rus:'авторизация'},
    {id:261,eng:'reminde',rus:'напоминать'},
    {id:262,eng:'access',rus:'доступ'},
    {id:263,eng:'determine',rus:'определять'},
    {id:264,eng:'ourselves',rus:'самостоятельно'},
    {id:265,eng:'look up',rus:'искать'},
    {id:266,eng:'lookup table',rus:'таблица поиска'},
    {id:267,eng:'loop',rus:'обработать в цикле'},
    {id:268,eng:'tap into',rus:'подключиться'},
    {id:269,eng:'stroke',rus:'инсульт'},
    {id:270,eng:'rather',rus:'раньше (скорее)'},
    {id:271,eng:'looking for',rus:'находясь в поиске'},
    {id:272,eng:'predefined',rus:'предопределенный'},
    {id:273,eng:'here',rus:'здесь'},
    {id:274,eng:'empty',rus:'пустой'},
    {id:275,eng:'wasted effort',rus:'напрасные усилия'},
    {id:276,eng:'dive',rus:'нырять'},
    {id:277,eng:'solve',rus:'решать'},
    {id:278,eng:'behind',rus:'позади'},
    {id:279,eng:'benefits',rus:'преимущества'},
    {id:280,eng:'utility',rus:'полезность'},
    {id:281,eng:'overwrite',rus:'перезаписывать'},
    {id:282,eng:'frequent',rus:'частый'},
    {id:283,eng:'themselves',rus:'сами себя'},
    {id:284,eng:'capabilities',rus:'возможности'},
    {id:285,eng:'explicit',rus:'явный'},
    {id:286,eng:'such',rus:'такой'},
    {id:287,eng:'expect',rus:'предвидеть'},
    {id:288,eng:'sense',rus:'смысл'},
    {id:289,eng:'condition',rus:'условие (задачи)'},
    {id:290,eng:'excerpt',rus:'отрывок, выписка'},
    {id:291,eng:'familiar',rus:'знакомый'},
    {id:292,eng:'directly',rus:'напрямую (движение)'},
    {id:293,eng:'whenever',rus:'всякий раз'},
    {id:294,eng:'by the time',rus:'к тому времени'},
    {id:295,eng:'screw',rus:'винт'},
    {id:296,eng:'ahead of time',rus:'досрочно'},
    {id:297,eng:'allow',rus:'позволять'},
    {id:298,eng:'statement',rus:'оператор'},
    {id:299,eng:'entities',rus:'сущности'},
    {id:300,eng:'equal',rus:'равный'},
    {id:301,eng:'behav',rus:'веcти себя'},
    {id:302,eng:'that make up',rus:'из которых состоит'},
    {id:303,eng:'approach',rus:'подход'},
    {id:304,eng:'ask',rus:'просить'},
    {id:305,eng:'feedback',rus:'обратная связь'},
    {id:306,eng:'above',rus:'выше по тексту'},
    {id:307,eng:'implicit',rus:'неявный'},
    {id:308,eng:'sequence',rus:'последовательность'},
    {id:309,eng:'---',rus:'---'},
    {id:310,eng:'mean',rus:'означать, иметь ввиду'},
    {id:311,eng:'consumer',rus:'потребитель'},
    {id:312,eng:'within',rus:'в пределах'},
    {id:313,eng:'responsibilities',rus:'обязанности'},
    {id:314,eng:'recent',rus:'недавний'},
    {id:315,eng:'whether',rus:'ли'},
    {id:316,eng:'necessary',rus:'необходимый'},
    {id:317,eng:'although',rus:'не смотря на то что'},
    {id:318,eng:'seem',rus:'казаться'},
    {id:319,eng:'supply',rus:'поставлять'},
    {id:320,eng:'until',rus:'до того как'},
    {id:321,eng:'notice',rus:'Обратите внимание'},
    {id:322,eng:'order',rus:'порядок'},
    {id:323,eng:'keep',rus:'содержать, хранить'},
    {id:324,eng:'in order',rus:'в целях'},
    {id:325,eng:'itself',rus:'сам'},
    {id:326,eng:'turns out',rus:'оказывается'},
    {id:327,eng:'same',rus:'такойже'},
    {id:328,eng:'outer',rus:'внешний'},
    {id:329,eng:'so far',rus:'до сих пор'},
    {id:330,eng:'кeep',rus:'держать'},
    {id:331,eng:'actually',rus:'фактически'},
    {id:332,eng:'compare',rus:'сравнивать'},
    {id:333,eng:'useful',rus:'полезный, функциональный'},
    {id:334,eng:'introduction',rus:'введение'},
    {id:335,eng:'especially',rus:'особенно'},
    {id:336,eng:'started off',rus:'начанались (зародились)'},
    {id:337,eng:'distribut',rus:'распределять'},
    {id:338,eng:'note',rus:'примечание'},
    {id:339,eng:'view',rus:'смотреть'},
    {id:340,eng:'plug',rus:'затыкать'},
    {id:341,eng:'consider',rus:'рассматривать'},
    {id:342,eng:'define',rus:'определять переменную'},
    {id:343,eng:'order',rus:'заказывать'},
    {id:344,eng:'---',rus:'---'},
    {id:345,eng:'latest',rus:'последний'},
    {id:346,eng:'able',rus:'способный'},
    {id:347,eng:'---',rus:'--'},
    {id:348,eng:'apparent',rus:'явный'},
    {id:349,eng:'prefer',rus:'предпочитать'},
    {id:350,eng:'compatibility',rus:'совместимость'},
    {id:351,eng:'assume',rus:'предполагать'},
    {id:352,eng:'become',rus:'становиться'},
    {id:353,eng:'receive',rus:'получать'},
    {id:354,eng:'appear',rus:'появляться'},
    {id:355,eng:'particular',rus:'конкретный'},
    {id:356,eng:'сaveat',rus:'предостережение'},
    {id:357,eng:'along',rus:'вместе'},
    {id:358,eng:'ither',rus:'либо'},
    {id:359,eng:'assign',rus:'назначить'},
    {id:360,eng:'almost',rus:'почти'},
    {id:361,eng:'require',rus:'требовать'},
    {id:362,eng:'lack',rus:'недостаток'},
    {id:363,eng:'differ',rus:'отличаться'},
    {id:364,eng:'abusin',rus:'злоупотребление'},
    {id:365,eng:'---',rus:'---'},
    {id:366,eng:'---',rus:'---'},
    {id:367,eng:'---',rus:'---'},
    {id:368,eng:'---',rus:'---'},
    {id:369,eng:'---',rus:'---'},
    {id:370,eng:'---',rus:'---'},
    {id:371,eng:'---',rus:'---'},
    {id:372,eng:'interact',rus:'взаимодействовать'},
    {id:373,eng:'suggest',rus:'предлагать'},
    {id:374,eng:'prevent',rus:'предотвращать'},
    {id:375,eng:'mistake',rus:'ошибка'},
    {id:376,eng:'describe',rus:'описывать'},
    {id:377,eng:'occur',rus:'происходить'},
    {id:378,eng:'break down',rus:'авария, поломка'},
    {id:379,eng:'trigger',rus:'спусковой механизм'},
    {id:380,eng:'matter',rus:'иметь значение'},
    {id:381,eng:'enforcing rules',rus:'соблюдение правил'},
    {id:382,eng:'predict',rus:'предсказывать'},
    {id:383,eng:'amend',rus:'исправить'},
    {id:384,eng:'threshold',rus:'порог'},
    {id:385,eng:'checkout',rus:'проверить'},
    {id:386,eng:'cause',rus:'причина'},
    {id:387,eng:'commit',rus:'фиксировать'},
    {id:388,eng:'worry',rus:'волноваться'},
    {id:389,eng:'ensures',rus:'гарантирует'},
    {id:390,eng:'discard',rus:'отказаться'},
    {id:391,eng:'racial',rus:'рассовый'},
    {id:392,eng:'divide',rus:'разделять'},
    {id:393,eng:'leak',rus:'утечка'},
    {id:394,eng:'scores',rus:'баллы'},
    {id:395,eng:'resign',rus:'уйти в отставку'},
    {id:396,eng:'convers',rus:'беседовать'},
    {id:397,eng:'insult',rus:'оскорблять'},
    {id:398,eng:'slurs',rus:'оскорбления'},
    {id:399,eng:'deploy',rus:'развернуть'},
    {id:400,eng:'scratch',rus:'царапать'},
    {id:401,eng:'temporary',rus:'временный'},
    {id:402,eng:'match',rus:'соответствие, совподение'},
    {id:403,eng:'succss',rus:'успех'},
    {id:404,eng:'former',rus:'бывший'},
    {id:405,eng:'ease',rus:'простота'},
    {id:406,eng:'treasure',rus:'сокровищница'},
]
